let startBtn = document.getElementById('start'),
  budget = document.querySelectorAll('.budget-value'),
  daybudget = document.querySelectorAll('.daybudget-value'),
  level = document.querySelectorAll('.level-value'),
  expenses = document.querySelectorAll('.expenses-value'),
  optionalexpenses = document.querySelectorAll('.optionalexpenses-value'),
  income = document.querySelectorAll('.income-value'),
  monthsavings = document.querySelectorAll('.monthsavings-value'),
  checkbox = document.querySelector('#savings'),
  sum = document.querySelector('#sum'),
  percent = document.querySelector('#percent'),
  yearsavings = document.querySelectorAll('.yearsavings-value'),
  year = document.querySelectorAll('.year-value'),
  month = document.querySelectorAll('.month-value'),
  day = document.querySelectorAll('.day-value'),
  choose = document.querySelector('.choose-income'),

  buttons = document.getElementsByTagName('button'),
  accept1 = document.querySelector('.expenses-item-btn'),
  accept2 = document.querySelector('.optionalexpenses-btn'),
  count = document.querySelector('.count-budget-btn');

